# Generated by Django 5.2.7 on 2026-03-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=512, unique=True)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('link', models.URLField(blank=True, max_length=2048)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=256)),
                ('site', models.CharField(blank=True, max_length=128)),
                ('source', models.CharField(blank=True, max_length=512)),
                ('creator', models.CharField(blank=True, max_length=256)),
                ('author', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('identifier', models.CharField(blank=True, max_length=256)),
                ('keyword', models.CharField(blank=True, max_length=512)),
                ('threat_level', models.CharField(blank=True, max_length=128)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('pull_date', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='newsfeed.tag')),
            ],
            options={
                'ordering': ['-pub_date', '-pull_date'],
            },
        ),
    ]
